### ISSUE TITLE
towncrier is broken on Python 2.7

### ISSUE THREAD

**Issue by exarkun** [hawkowl/towncrier#121]
```
$ towncrier --draft
Loading template...
Finding news fragments...
Rendering news fragments...
Traceback (most recent call last):
  File ".../bin/towncrier", line 11, in <module>
    sys.exit(_main())
  File ".../lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File ".../lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File ".../lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File ".../lib/python2.7/site-packages/towncrier/__init__.py", line 54, in _main
    draft, directory, project_name, project_version, project_date, answer_yes
  File ".../lib/python2.7/site-packages/towncrier/__init__.py", line 93, in __main
    fragments = split_fragments(fragments, definitions)
  File ".../lib/python2.7/site-packages/towncrier/_builder.py", line 87, in split_fragments
    content = textwrap.indent(content.strip(), "  ")[2:]
AttributeError: 'module' object has no attribute 'indent'
```

**Comment by exarkun** [comment]
As a result, it is impossible to use towncrier with Python 2-only software.  This seems like an unfortunate and unnecessary circumstance.

**Comment by mauritsvanrees** [comment]
👍 for making a new release that works on Python 2.
